---
- name: "Update apt-get cache"
  apt:
    update_cache: yes

- name: PHP | install packages to allow download from ssl urls.
  apt: pkg={{ item }} state=installed
  with_items:
    - software-properties-common
    - python-software-properties

- name: Mailhog| Install Mailhog
  get_url:
    url: {{ mailhog_release_url }}
    dest: {{ mailhog_install_path }}
    owner: root
    group: root
    mode: 0755
